version: '3.8'

services:
  user-service:
    image: emilijadn/ita-user-service-image:1.0.0
    ports:
      - "8080:8080"
    depends_on:
      - mongo_db
    environment:
      SPRING_DATA_MONGODB_URI: ${MONGO_DB_URI}
      SPRING_DATA_MONGODB_DATABASE: ${MONGO_DB_DATABASE}
    networks:
      - my-network

  membership-service:
    image: emilijadn/ita-membership-service:2.0.0
    ports:
      - "9000:9000"
    depends_on:
      - mongo_db
    environment:
      MONGO_DB_URI_MS: ${MONGO_DB_URI_MS}
      MONGO_DB_DATABASE_MS: ${MONGO_DB_DATABASE_MS}
    networks:
      - my-network

  group-classes-service:
    image: emilijadn/ita-group-classes-service-image:1.0.0
    ports:
      - "8081:8080" # Changed port to avoid conflict with user-service
    depends_on:
      - mongo_db
      - artemis
    environment:
      MONGO_DB_URI_GCS: ${MONGO_DB_URI_GCS}
      MONGO_DB_URI_GCS_TEST: ${MONGO_DB_URI_GCS_TEST}
      MONGO_DB_DATABASE_GCS: ${MONGO_DB_DATABASE_GCS}
      QUARKUS_ARTEMIS_URL: tcp://artemis:61616
    networks:
      - my-network

  mongo_db:
    image: mongo:7.0.6
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - my-network

  artemis:
    image: vromero/activemq-artemis:latest
    ports:
      - "8161:8161"  # Web Console
      - "61616:61616" # AMQP Port
      - "5445:5445"   # Core Port
    networks:
      - my-network
  
  mobile-gateway:
    image: emilijadn/ita-mobile-gateway:1.0.0
    ports:
      - "4000:4000"
    depends_on:
      - user-service
      - group-classes-service
      - membership-service
    networks:
      - my-network
  
  web-gateway:
    image: emilijadn/ita-web-gateway:2.0.0
    ports:
      - "3000:3000"
    depends_on:
      - user-service
      - group-classes-service
      - membership-service
    networks:
      - my-network
  
  # micro-frontend-home:
  #   image: emilijadn/ita-micro-frontend-home:1.0.0
  #   ports:
  #     - "3001:3001"
  #   networks:
  #     - my-network
  

  # micro-frontend-user:
  #   image: emilijadn/ita-micro-frontend-user:1.0.0
  #   ports:
  #     - "3002:3002"
  #   networks:
  #     - my-network
  
  # micro-frontend-membership:
  #   image: emilijadn/ita-micro-frontend-membership:1.0.0
  #   ports:
  #     - "3003:3003"
  #   networks:
  #     - my-network

  # micro-frontend-groupclass:
  #   image: emilijadn/ita-micro-frontend-groupclass:1.0.0
  #   ports:
  #     - "3004:3004"
  #   networks:
  #     - my-network
    
networks:
  my-network:
    driver: bridge

volumes:
  mongo-data:
