version: '3.8'

services:
  membership-service:
    image: emilijadn/ita-membership-service:2.0.0
    ports:
      - "9000:9000"
    depends_on:
      - mongo_db
    environment:
      MONGO_DB_URI_MS: ${MONGO_DB_URI_MS}
      MONGO_DB_DATABASE_MS: ${MONGO_DB_DATABASE_MS}

  mongo_db:
    image: mongo:7.0.6
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
