version: '3.8'

services:
  membership-service:
    image: emilijadn/ita-membership-service-jvm:1.0.0
    ports:
      - "8080:8080"
    depends_on:
      - mongo_db
    environment:
      SPRING_DATA_MONGODB_URI_MS: ${MONGO_DB_URI_MS}
      SPRING_DATA_MONGODB_DATABASE_MS: ${MONGO_DB_DATABASE_MS}

  mongo_db:
    image: mongo:7.0.6
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
