name: Run Tests (Group Classes Service)

on:
  push:
    branches:
      - master  

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      QUARKUS_ARTEMIS_URL: ${{ secrets.QUARKUS_ARTEMIS_URL }}
      MONGO_DB_URI_GCS: ${{ secrets.MONGO_DB_URI_GCS }}
      MONGO_DB_DATABASE_GCS: ${{ secrets.MONGO_DB_DATABASE_GCS }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.10.0
      with:
        mongodb-version: 7.0.6

    - name: Start Artemis Broker
      run: docker run --name artemis-broker -d -p 61616:61616 -p 8161:8161 vromero/activemq-artemis

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'maven'

    - name: Build and test with Maven
      working-directory: ./group-classes-service
      run: mvn -B clean install