name: Build and Publish Docker Image (Health check)

on:
  push:
    branches:
      - master  

jobs:
  build_and_publish:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: emilijadn/ita-health-check-service-image
      TAG: 1.0.0

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Log in to Docker Hub
      uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build and push Docker image
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: ./health-check-service
        file: ./health-check-service/Dockerfile
        push: true
        tags: ${{ env.IMAGE_NAME }}:${{ env.TAG }}
